import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { ClerkProvider } from "@clerk/nextjs";

import "react-loading-skeleton/dist/skeleton.css";
import { ToasterProvider } from "@/providers/toast-provider";
import { ResumeContextProvider } from "./context/resume-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn("min-h-screen font-sans antialiased", inter.className)}
        >
          <ToasterProvider />
          <Navbar />
          <ResumeContextProvider>{children}</ResumeContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
